### ISSUE TITLE
Как лучше в CSS

### ISSUE THREAD

**Issue by Boffeer** [Petr791/BURGER.CO#4]
Подключай шрифты не с гугл фонтс, а локально. Сейчас подключение с гугл фонтс не дает никаких преимуществ.
Скачиваешь шрифты на гугл фонтс, если есть в формате ttf. Нужные начертания закидываешь на transfonter.org, оттуда в итоге получаешь  архив, где будут файлы woff и woff2. Их закидываешь в папку fonts своего проекта.

Затем в css подключаешь шрифты. 
В архиве с transfonter будет  css файл с подключением каждого шрифта. Ты этот текст копируешь и вставляешь в свой scss
Только в каждый `@font-face` добавь еще свойство `font-display: swap;`, это сделает загрузку быстрее визуально

---

```css
body {
    /* 
       Если подключаемый шрифт с засечками, то в конце font-family пишешь serif
       Если подключаешь шрифт вез засечек, то в конце пишешь sans-serif
       Это нужно, что при загрузке страницы, грузящиеся шрифты слабо отличались друг от друга.
    */
    font-family: 'Martel', serif;

}


/* @burgers  комент с названием секции можешь начинать с «@», чтобы было проще поиском найти его*/

По адаптиву вопросов нет, все хорошо перестраивается, резиново

```
